name: staging_deployment

on:
  issue_comment:
    types: [created]

jobs:

  deploy-web:
    runs-on: ubuntu-latest
    steps:

      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          
      - name: get pull request ref
        id: get_pull_request_ref
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:repository/pulls/:issue_id
          repository: ${{ github.repository }}
          issue_id: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "clone repos"
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}
        if: steps.check.outputs.triggered == 'true'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          
      - name: "Checkout to a branch"
        run: |
          BRANCH="${{ fromJson(steps.get_pull_request_ref.outputs.data).head.ref }}"
          echo "Checking out from branch $BRANCH"
          git branch
          git log 
        if: steps.check.outputs.triggered == 'true'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: "Deploy"
        run: |
          # deployment logic goes here
          ls -ah
          cat index.html
