name: staging_deployment

on:
  issue_comment:
    types: [created]

jobs:

  deploy-web:
    runs-on: ubuntu-latest
    steps:

      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/deploy'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: "Checkout to the current branch"
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        if: steps.check.outputs.triggered == 'true'
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: "Deploy"
        run: |
          # deployment logic goes here
          ls -ah
          cat index.html
